routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/','TestingViewController@index');
Route::post('/email-contact', 'ContactController@sendEmailContact')->name('email-contact');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('/service', 'ServicesController')->only('index','update','edit', 'create','store','destroy');
});

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/asd','TestingViewController@index');

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $fillable   = [
        'title',
        'description',
        'image_path'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use UxWeb\SweetAlert;

class ContactController extends Controller
{
    public function sendEmailContact(Request $request)
    {

        $name = $request->input('name').' '.$request->input('last_name');

        $userEmail = $request->input('email');
        $phone = $request->input('phone');
        $message = $request->input('message');

        $data = [
            'userName' => $name,
            'userEmail' => $userEmail,
            'userPhone' => $phone,
            'subject' => $message
        ];

        Mail::send('admin.notifications.contact-user-admin', $data, function($message){
                $message->to(env('MAIL_USERNAME_ME'))
                ->subject("Una persona se ha puesto en contacto con SVManagement");
        });

        alert()->success('Hemos notificado correctamente tu solicitud', 'Pronto estaremos en contacto contigo')->persistent();
        return redirect()->back();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ServicesController.php
<?php

namespace App\Http\Controllers;

use App\Service;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use UxWeb\SweetAlert\SweetAlert;

class ServicesController extends Controller
{

    public function index()
    {
        $services = Service::paginate(3);
        return view('admin.services.index', compact('services'));
    }


    public function create(Request $request)
    {
        return view('admin.services.create');
    }


    public function store(Request $request)
    {
        //dd($request->all());
            if ($request->hasFile('image')){

                $image      = $request->file('image');
                $fileName   = $image->getClientOriginalName();

                $img = Image::make($image->getRealPath());

                /*$img->resize(1000, 750, function ($constraint) {
                    $constraint->aspectRatio();
                });*/

                $img->stream(); // <-- Key point
                $saved =  Storage::disk('local')->put('public/images/services'.'/'.$fileName, $img, 'public');
                $path = 'images/services'.'/'.$fileName;
            }

            $service = Service::create([
                'title' => $request->input('title'),
                'description' => $request->input('description'),
                'image_path' => $path
            ]);

            alert()->success('Servicio creado correctamente!')->persistent('Cerrar');

        return redirect()->route('service.index');
    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $service = Service::find($id);
        return view('admin.services.edit', compact('id','service'));
    }


    public function update(Request $request, $id)
    {
        $service = Service::find($id);

        $service->update([
                'title' => $request->input('title'),
                'description' => $request->input('description')
            ]);

        alert()->success('Servicio editado correctamente!')->persistent('Cerrar');
        return redirect()->route('service.index');
    }


    public function destroy($id)
    {
        $service = Service::find($id);

        if ($service){
            $service->delete();
        }

        alert()->success('Servicio eliminado correctamente!')->persistent('Cerrar');
        return redirect()->route('service.index');
    }
}

app/Http/Controllers/TestingViewController.php
<?php

namespace App\Http\Controllers;

use App\Service;
use Illuminate\Http\Request;

class TestingViewController extends Controller
{
    public function index()
    {
        //dd("Penes desde aca");
        $services = Service::all();
        //dd($services);
        return view('home.index', compact('services'));
    }
}

resources/views/admin/layouts/navbar.blade.php
<style>

    .navbar-brand {
        float: left;
        height: 50px;
        padding: 10px 10px;
        font-size: 18px;
        line-height: 20px;
        margin-top: -17px;
    }
</style>
<header id="navigation" class="navbar navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="/">
                <img src="{{ asset("images/minilogo2.png")}}" alt="Website Logo" />
            </a>

        </div>

        <nav class="collapse navbar-collapse navbar-right" role="Navigation">
            <ul id="nav" class="nav navbar-nav navigation-menu">
                <li><a data-scroll href="/">Inicio</a></li>
                <li>
                    <a data-scroll href="{{ route('logout') }}" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        Cerrar Sesion</a></li>
            </ul>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </nav>
    </div>
</header>

resources/views/admin/services/create.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="ltr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="description" content="Artist Management Agency ">

    <meta name="author" content="Muhammad Morshed">

    <title>SV | Management</title>
    <link rel="shortcut icon" href="{{ asset('images/favicon.png') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ asset('plugins/themefisher-font/style.css') }}">
    <!-- bootstrap.min css -->
    <link rel="stylesheet" href="{{ asset('plugins/bootstrap/dist/css/bootstrap.min.css')}}" >
    <!-- Animate.css -->
    <link rel="stylesheet href="{{ asset('plugins/animate-css/animate.css')}} >
    <!-- Magnific popup css -->
    <link rel="stylesheet" href="{{ asset('plugins/magnific-popup/dist/magnific-popup.css')}}" >
    <!-- Slick Carousel -->
    <link rel="stylesheet" href="{{ asset('plugins/slick-carousel/slick/slick.css')}}" >
    <link rel="stylesheet" href="{{ asset('plugins/slick-carousel/slick/slick-theme.css')}}" >
    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="{{ asset('css/style.css')}}" >

    @yield('styles')

</head>
<body id="body" data-spy="scroll" data-target=".navbar" data-offset="50">

@include('admin.layouts.navbar')

<section>
    <div class="container">
        <div class="title text-center wow fadeIn" data-wow-duration="500ms">
            <h2><span class="color">Crear Servicio</span></h2>
            <div class="border"></div>
        </div>
        <div class="row">
            @include('admin.services.forms')
        </div>
    </div>
</section>
@include('sweet::alert')
@include('layouts.footer')
<!-- Main jQuery -->
<script type="text/javascript" src="{{ asset('plugins/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap 3.1 -->
<script type="text/javascript"  src="{{ asset('plugins/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- Slick Carousel -->
<script type="text/javascript" src="{{ asset('plugins/slick-carousel/slick/slick.min.js') }}"></script>
<!-- Portfolio Filtering -->
<script type="text/javascript" src="{{ asset('plugins/filterzr/jquery.filterizr.min.js') }}"></script>
<!-- Smooth Scroll -->
<script type="text/javascript" src="{{ asset('plugins/smooth-scroll/dist/js/smooth-scroll.min.js') }}"></script>
<!-- Magnific popup -->
<script type="text/javascript" src="{{ asset('plugins/magnific-popup/dist/jquery.magnific-popup.min.js') }}"></script>
<!-- Google Map API -->
{{--<script type="text/javascript"  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"></script>--}}
<!-- Sticky Nav -->
<script type="text/javascript" src="{{ asset('plugins/Sticky/jquery.sticky.js') }}"></script>
<!-- Number Counter Script -->
<script type="text/javascript" src="{{ asset('plugins/count-to/jquery.countTo.js') }}"></script>
<!-- wow.min Script -->
<script type="text/javascript" src="{{ asset('plugins/wow/dist/wow.min.js') }}"></script>
<!-- Custom js -->
<script type="text/javascript" src="{{ asset('js/script.js') }}"></script>

@yield('scripts')

</body>
</html>

resources/views/admin/services/edit.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="ltr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="description" content="Artist Management Agency ">

    <meta name="author" content="Muhammad Morshed">

    <title>SV | Management</title>
    <link rel="shortcut icon" href="{{ asset('images/favicon.png') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ asset('plugins/themefisher-font/style.css') }}">
    <!-- bootstrap.min css -->
    <link rel="stylesheet" href="{{ asset('plugins/bootstrap/dist/css/bootstrap.min.css')}}" >
    <!-- Animate.css -->
    <link rel="stylesheet href="{{ asset('plugins/animate-css/animate.css')}} >
    <!-- Magnific popup css -->
    <link rel="stylesheet" href="{{ asset('plugins/magnific-popup/dist/magnific-popup.css')}}" >
    <!-- Slick Carousel -->
    <link rel="stylesheet" href="{{ asset('plugins/slick-carousel/slick/slick.css')}}" >
    <link rel="stylesheet" href="{{ asset('plugins/slick-carousel/slick/slick-theme.css')}}" >
    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="{{ asset('css/style.css')}}" >

    @yield('styles')

</head>
<body id="body" data-spy="scroll" data-target=".navbar" data-offset="50">

@include('layouts.navbar')

<section>
    <div class="container">
        <div class="title text-center wow fadeIn" data-wow-duration="500ms">
            <h2><span class="color">Editar Servicio</span></h2>
            <div class="border"></div>
        </div>
        <div class="row">
            @include('admin.services.forms')
        </div>
    </div>
</section>
@include('sweet::alert')
@include('layouts.footer')
<!-- Main jQuery -->
<script type="text/javascript" src="{{ asset('plugins/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap 3.1 -->
<script type="text/javascript"  src="{{ asset('plugins/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- Slick Carousel -->
<script type="text/javascript" src="{{ asset('plugins/slick-carousel/slick/slick.min.js') }}"></script>
<!-- Portfolio Filtering -->
<script type="text/javascript" src="{{ asset('plugins/filterzr/jquery.filterizr.min.js') }}"></script>
<!-- Smooth Scroll -->
<script type="text/javascript" src="{{ asset('plugins/smooth-scroll/dist/js/smooth-scroll.min.js') }}"></script>
<!-- Magnific popup -->
<script type="text/javascript" src="{{ asset('plugins/magnific-popup/dist/jquery.magnific-popup.min.js') }}"></script>
<!-- Google Map API -->
{{--<script type="text/javascript"  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"></script>--}}
<!-- Sticky Nav -->
<script type="text/javascript" src="{{ asset('plugins/Sticky/jquery.sticky.js') }}"></script>
<!-- Number Counter Script -->
<script type="text/javascript" src="{{ asset('plugins/count-to/jquery.countTo.js') }}"></script>
<!-- wow.min Script -->
<script type="text/javascript" src="{{ asset('plugins/wow/dist/wow.min.js') }}"></script>
<!-- Custom js -->
<script type="text/javascript" src="{{ asset('js/script.js') }}"></script>

@yield('scripts')

</body>
</html>

resources/views/admin/services/forms.blade.php
{!! Form::open([
        'route' => isset($id) ? ['service.update', $id] : 'service.store',
        'method' => isset($id) ? 'PUT' : 'POST',
        'files' => true,
        'class' => 'needs-validation',
        'novalidate' => 'novalidate',
    ])
!!}
    <div class="form-group">
        {!! Form::label('title', 'Titulo') !!}
        {!! Form::text('title', isset($service)? $service->title : null, ['class' => 'form-control', 'placeholder' =>"Ingresa un titulo", 'id' => 'title']) !!}
    </div>

    <div class="form-group">
        {!! Form::label('description', 'Descripcion') !!}
        {!! Form::textarea('description', isset($service)? $service->description : null, ['class' => 'form-control', 'placeholder' =>"Ingresa una descripción", 'id' => 'description', 'onCopy' => "return true"]) !!}
    </div>

    <div class="form-group">
        {!! Form::label('image', 'Imagen de referencia') !!}
        {!! Form::file('image',['class' =>"form-control", "name"=>"image" , "id"=>"image"]); !!}
    </div>

    <div class="row">
        <div class="col-12">
            {!! Form::submit((isset($id)) ? 'Editar' : 'Crear', ['class' => 'btn btn-transparent', 'id' => 'contact-submit'])!!}
            <a href="{{ route('service.index') }}" class="btn btn-transparent" id="contact-submit">Regresar</a>

        </div>
    </div>
{!! Form::close() !!}

resources/views/admin/services/index.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="ltr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="description" content="Artist Management Agency ">

    <meta name="author" content="Muhammad Morshed">

    <title>SV | Management</title>
    <link rel="shortcut icon" href="{{ asset('images/favicon.png') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ asset('plugins/themefisher-font/style.css') }}">
    <!-- bootstrap.min css -->
    <link rel="stylesheet" href="{{ asset('plugins/bootstrap/dist/css/bootstrap.min.css')}}" >
    <!-- Animate.css -->
    <link rel="stylesheet href="{{ asset('plugins/animate-css/animate.css')}} >
    <!-- Magnific popup css -->
    <link rel="stylesheet" href="{{ asset('plugins/magnific-popup/dist/magnific-popup.css')}}" >
    <!-- Slick Carousel -->
    <link rel="stylesheet" href="{{ asset('plugins/slick-carousel/slick/slick.css')}}" >
    <link rel="stylesheet" href="{{ asset('plugins/slick-carousel/slick/slick-theme.css')}}" >
    <!-- Main Stylesheet -->
    <link rel="stylesheet" href="{{ asset('css/style.css')}}" >
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    @yield('styles')

</head>
<body id="body" data-spy="scroll" data-target=".navbar" data-offset="50">

@include('admin.layouts.navbar')
{{--@include('layouts.video-slider')--}}
{{--@include('layouts.contact-form')--}}

<section>
    <div class="container">

        <div class="title text-center wow fadeIn" data-wow-duration="500ms">
            <h2><span class="color">Servicios</span></h2>
            <div class="border"></div>
            <a class="btn btn-transparent pull-right" href="/service/create">Agregar</a>
        </div>

        @if($services->isEmpty())
            <div class="card-body">
                <div class="alert alert-info">{{__('forms.No Services available')}}</div>
            </div>
        @else
        <div class="table-responsive-md">
            <table class="table table-sm" style="width:100%">
                <thead>
                <tr>
                    <th>Titulos</th>
                    <th>Descripción</th>
                    <th>Imagen</th>
                </tr>
                </thead>
                <tbody>
                @foreach($services as $service)
                <tr>
                    <td>{{$service->title}}</td>
                    <td>{{$service->description}}</td>
                    <td>
                        {{--<img src="{{ asset('storage/'.$service->image_path) }}"></img>--}}
                        <img class="img-responsive" src="{{ asset('storage/'.$service->image_path) }}" alt="Meghna">
                    </td>
                    <td>
                        <a class="btn btn-transparent align-items-center" href="{{route("service.edit", $service->id)}}">Editar</a>

                        {!! Form::open(['route' => ['service.destroy', $service->id], 'method' => 'DELETE']) !!}
                        {!! Form::submit('Borrar', ['class' => 'btn btn-transparent align-items-center']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
                @endforeach
                </tbody>
                <tfoot>
                {!! $services->links() !!}
                </tfoot>
            </table>
        </div>
        @endif

    </div>
</section>
@include('sweet::alert')
@include('layouts.footer')
<!-- Main jQuery -->
<script type="text/javascript" src="{{ asset('plugins/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap 3.1 -->
<script type="text/javascript"  src="{{ asset('plugins/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- Slick Carousel -->
<script type="text/javascript" src="{{ asset('plugins/slick-carousel/slick/slick.min.js') }}"></script>
<!-- Portfolio Filtering -->
<script type="text/javascript" src="{{ asset('plugins/filterzr/jquery.filterizr.min.js') }}"></script>
<!-- Smooth Scroll -->
<script type="text/javascript" src="{{ asset('plugins/smooth-scroll/dist/js/smooth-scroll.min.js') }}"></script>
<!-- Magnific popup -->
<script type="text/javascript" src="{{ asset('plugins/magnific-popup/dist/jquery.magnific-popup.min.js') }}"></script>
<!-- Google Map API -->
{{--<script type="text/javascript"  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"></script>--}}
<!-- Sticky Nav -->
<script type="text/javascript" src="{{ asset('plugins/Sticky/jquery.sticky.js') }}"></script>
<!-- Number Counter Script -->
<script type="text/javascript" src="{{ asset('plugins/count-to/jquery.countTo.js') }}"></script>
<!-- wow.min Script -->
<script type="text/javascript" src="{{ asset('plugins/wow/dist/wow.min.js') }}"></script>
<!-- Custom js -->
<script type="text/javascript" src="{{ asset('js/script.js') }}"></script>

@yield('scripts')

</body>
</html>

resources/views/home.blade.php
@extends('layouts.awpp')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home/index.blade.php
@extends('layouts.master')

resources/views/layouts/about-us.blade.php
<!--
		Start About Section
		==================================== -->
<section class="bg-one about section">
    <div class="container">
        <div class="row">

            <!-- section title -->
            <div class="title text-center wow fadeIn" data-wow-duration="1500ms" >
                <h2>About <span class="color">Us</span> </h2>
                <div class="border"></div>
            </div>
            <!-- /section title -->

            <!-- About item -->
            <div class="col-md-12 text-center wow fadeInUp" data-wow-duration="500ms" data-wow-delay="250ms">
                <div class="block">
                    <div class="icon-box">
                        <i class="tf-strategy"></i>
                    </div>
                    <!-- Express About Yourself -->
                    <div class="content text-center">
                        <h3>¿QUIENES SOMOS?</h3>
                        <p>Somos una agencia de desarrollo artístico y management 360 de la ciudad de Bogotá, Colombia, gerenciamos, direccionamos, ejecutamos y asesoramos proyectos de índole musical para el óptimo posicionamiento de nuestros clientes en el mercado. </p>
                    </div>
                </div>
            </div>
            <!-- End About item -->


        </div> 		<!-- End row -->
    </div>   	<!-- End container -->
</section>   <!-- End section -->

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/counter.blade.php
<!--
Start Counter Section
==================================== -->

<section id="counter" class="parallax-section bg-1 section overly">
    <div class="container">
        <div class="row">

            <!-- first count item -->
            <div class="col-md-3 col-sm-6 col-xs-12 text-center wow fadeInDown" data-wow-duration="500ms">
                <div class="counters-item">
                    <i class="tf-ion-android-happy"></i>
                    <span data-speed="3000" data-to="320">320</span>
                    <h3>Happy Clients</h3>
                </div>
            </div>
            <!-- end first count item -->

            <!-- second count item -->
            <div class="col-md-3 col-sm-6 col-xs-12 text-center wow fadeInDown" data-wow-duration="500ms" data-wow-delay="200ms">
                <div class="counters-item">
                    <i class="tf-ion-archive"></i>
                    <span data-speed="3000" data-to="565">565</span>
                    <h3>Projects completed</h3>
                </div>
            </div>
            <!-- end second count item -->

            <!-- third count item -->
            <div class="col-md-3 col-sm-6 col-xs-12 text-center wow fadeInDown" data-wow-duration="500ms" data-wow-delay="400ms">
                <div class="counters-item">
                    <i class="tf-ion-thumbsup"></i>
                    <span data-speed="3000" data-to="95">95</span>
                    <h3>Positive feedback</h3>

                </div>
            </div>
            <!-- end third count item -->

            <!-- fourth count item -->
            <div class="col-md-3 col-sm-6 col-xs-12 text-center wow fadeInDown" data-wow-duration="500ms" data-wow-delay="600ms">
                <div class="counters-item kill-margin-bottom">
                    <i class="tf-ion-coffee"></i>
                    <span data-speed="3000" data-to="2500">2500</span>
                    <h3>Cups of Coffee</h3>
                </div>
            </div>
            <!-- end fourth count item -->

        </div> 		<!-- end row -->
    </div>   	<!-- end container -->
</section>   <!-- end section -->

resources/views/layouts/preloader.blade.php
<!--
    Start Preloader
    ==================================== -->
<div class="preloader">
    <div class="sk-cube-grid">
        <div class="sk-cube sk-cube1"></div>
        <div class="sk-cube sk-cube2"></div>
        <div class="sk-cube sk-cube3"></div>
        <div class="sk-cube sk-cube4"></div>
        <div class="sk-cube sk-cube5"></div>
        <div class="sk-cube sk-cube6"></div>
        <div class="sk-cube sk-cube7"></div>
        <div class="sk-cube sk-cube8"></div>
        <div class="sk-cube sk-cube9"></div>
    </div>
</div>
<!-- End Preloader
    ==================================== -->